version: '3'
services:
  php-apache:
    container_name: php-apache
    image: php:7.3-apache
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"